# Secrets dla workspace'u
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
type: Opaque
stringData:
  MLFLOW_TRACKING_URI: "http://mlflow.llm-workspace-template.svc.cluster.local:5000"
  MLFLOW_COMMON_URI: "http://mlflow-common.llm-shared.svc.cluster.local:5000"
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-db-secret
type: Opaque
stringData:
  POSTGRES_USER: "mlflow"
  POSTGRES_PASSWORD: "CHANGE_ME"
